root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
env:
  browser: true

plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'prettier'
rules:
  '@typescript-eslint/naming-convention':
    - warn
    - selector: function
      format: [PascalCase, camelCase]
  '@typescript-eslint/semi': warn
  curly: warn
  eqeqeq: warn
  no-empty-pattern: warn
  no-throw-literal: warn
  semi: 'off'
overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      no-undef: 'off'
      react/prop-types: 'off'