import { createTheme, DefaultPalette } from '@fluentui/react';

export const lightTheme = createTheme({
    palette: {
        themePrimary: '#0078d4',
        themeLighterAlt: '#eff6fc',
        themeLighter: '#deecf9',
        themeLight: '#c7e0f4',
        themeTertiary: '#71afe5',
        themeSecondary: '#2b88d8',
        themeDarkAlt: '#106ebe',
        themeDark: '#005a9e',
        themeDarker: '#004578',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    },
});

export const darkTheme = createTheme({
    palette: {
        themePrimary: '#0091ff',
        themeLighterAlt: '#00060a',
        themeLighter: '#001729',
        themeLight: '#002b4d',
        themeTertiary: '#005799',
        themeSecondary: '#007fe0',
        themeDarkAlt: '#199cff',
        themeDark: '#3dabff',
        themeDarker: '#70c1ff',
        neutralLighterAlt: '#1e1e1e',
        neutralLighter: '#282828',
        neutralLight: '#363636',
        neutralQuaternaryAlt: '#404040',
        neutralQuaternary: '#474747',
        neutralTertiaryAlt: '#666666',
        neutralTertiary: '#e2e2e2',
        neutralSecondary: '#e7e7e7',
        neutralPrimaryAlt: '#ebebeb',
        neutralPrimary: '#d4d4d4',
        neutralDark: '#f5f5f5',
        black: '#fafafa',
        white: '#141414',
        purple: '#9865cf',
        blackTranslucent40: DefaultPalette.whiteTranslucent40,
        whiteTranslucent40: DefaultPalette.blackTranslucent40,
    },
    isInverted: true,
});
